// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Codewithsteve.Microservices.BugsTracker.API;

namespace Codewithsteve.Microservices.BugsTrackerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Myairops.Tech.Test.ClientDatabase.Models.Bug", b =>
                {
                    b.Property<string>("BugId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BugCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ResolveByDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SignedoffBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatedFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("severitylevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BugId");

                    b.HasIndex("ClientId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("Myairops.Tech.Test.ClientDatabase.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserCreatedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatedFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreatedId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModifiedId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Myairops.Tech.Test.ClientDatabase.Models.Bug", b =>
                {
                    b.HasOne("Myairops.Tech.Test.ClientDatabase.Models.Client", "Client")
                        .WithMany("Bugs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
